AllCops:
  Exclude:
    - test/*
    - .git
    - .vscode
    - Gemfile

inherit_mode:
  merge:
    - Exclude

Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 1000
Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "test/**/*.rb"
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
